### ISSUE TITLE
Sending partial solution

### ISSUE THREAD

**Issue by Marwyk2003** [Pikne-Programy/pikne-zadania#14]
There is an issue with sending only a part of the problem's solution. (e.g. unknown x is calculated, while another unknown t is not)
Right now such a solution is considered invalid and would not be sent to the server.

**Comment by Nircek** [comment]
The user can try to guess what the proper value is. If they don't want to and leave the input blank (by e. g. sending through API `null`), the answer always will be incorrect. So the use of `null` is useless for public Exercise DataBase (ExDB). If we chose to send success info about each unknown instead of sending about the whole answer, it would be necessary.

**Comment by Nircek** [comment]
And the issue should stay open for future private ExDB. In my view, a teacher should somehow be able to claim how many points a student will gain for each calculated unknown.

**Comment by Nircek** [comment]
Okay, so you all want to implement this feature. I need to describe it in #1 so:
@MichalTheProgrammer how do you see this? What we have to send back through the API?

**Comment by Nircek** [comment]
We agreed that we don't deal with partial solutions in the v0.1 prototype, so the issue remains open for the future.

**Comment by Nircek** [comment]
@MichalTheProgrammer @Marwyk2003 if we don't add partial solutions in the v0.2 prototype, it will be tough doing so in future.
So how do you see supporting this?

**Comment by Nircek** [comment]
So we agreed about the API of this feature in #25. We will send the correctness of a solution by an array of bools.

**Comment by Nircek** [comment]
@Marwyk2003 did this functionality in a2fdc90a91f99616ef887db50f90a089739c8341. I'm closing.
